# Directory
root_dir: ./
exp_name: 1221_lightning_test

# Dataset options
device: cuda
N_src: 3
N_src_extra: 10

# Training options
N_rays: 800
pe_dim: 10
lr: 0.0005
n_iters: 50000

# Rendering options
chunk_size: 3200

# Ray and Point sampling options
N_samples: 32
N_importance: 16
inv_uniform: False
det: True
render_stride: 1
ray_sampling_mode: uniform
center_ratio: 0.8
# feature_padding_mode: zeros
# feature_interpolation_mode: bilinear

# Logging options
step_img: 2000
epoch_val_img: 2
step_loss: 100
step_weight: 5000