tensorboad:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "tensorboard/"
  name: donut_single_1
  # version: ${name}
  version: nerformer
  log_graph: False
  default_hp_metric: True
  prefix: ""