# Directory
root_dir: ./
out_dir: ./pl_out
exp_name: 0104_ray_sampling_center

# Dataset options
device: cuda
co3d_category: teddybear        #
co3d_task: singlesequence       #
co3d_single_sequence_id: 0      #
N_src: 3                        #
N_src_extra: 10                 #

# Training options
N_rays: 800     #
pe_dim: 10      #
lr: 0.0005      #
n_iters: 20000  #

# Rendering options
chunk_size: 3200    #

# Ray and Point sampling options
N_samples: 32                         #
N_importance: 16                      #
inv_uniform: False                    #
det: False                            #
render_stride: 1                      #
ray_sampling_mode: center             #
center_ratio: 0.8                     #
feature_padding_mode: zeros           #
feature_interpolation_mode: bilinear  #

# Logging options
log_img: True           #
log_img_step: 2000      #
epoch_val_img: 2        #
log_loss_step: 100      #
log_weight_step: 2000   #